before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X "github.com/corenting/cookies/internal/entities.AppVersion={{.Version}}"
archives:
  - id: cookies
    format: binary
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
