name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
      - name: Run tests (with coverage)
        run: make test
      - name: Build app
        run: make build
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest'
